import os
import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

class DocxExporter:
    @staticmethod
    def _set_cell_background(cell, color_hex):
        """Sets the background color of a table cell."""
        shading_elm = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{color_hex}"/>')
        cell._tc.get_or_add_tcPr().append(shading_elm)

    @staticmethod
    def _set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
        """Sets internal margins for a cell."""
        tcPr = cell._tc.get_or_add_tcPr()
        tcMar = OxmlElement('w:tcMar')
        for m, val in [('w:top', top), ('w:bottom', bottom), ('w:left', left), ('w:right', right)]:
            node = OxmlElement(m)
            node.set(qn('w:w'), str(val))
            node.set(qn('w:type'), 'dxa')
            tcMar.append(node)
        tcPr.append(tcMar)

    @staticmethod
    def _add_page_number(run):
        """Appends a page number field to a run (not trivial in python-docx, uses XML fields)."""
        fldChar1 = OxmlElement('w:fldChar')
        fldChar1.set(qn('w:fldCharType'), 'begin')
        instrText = OxmlElement('w:instrText')
        instrText.set(qn('xml:space'), 'preserve')
        instrText.text = "PAGE"
        fldChar2 = OxmlElement('w:fldChar')
        fldChar2.set(qn('w:fldCharType'), 'separate')
        fldChar3 = OxmlElement('w:fldChar')
        fldChar3.set(qn('w:fldCharType'), 'end')
        
        run._r.append(fldChar1)
        run._r.append(instrText)
        run._r.append(fldChar2)
        run._r.append(fldChar3)

    @classmethod
    def export(cls, event_info, venue_data, speaker_data, catering_data, logistics_data, comms_data, coordinator_data, output_path):
        """
        Generates a professionally styled Word document.
        """
        doc = docx.Document()
        
        # Set Page Margins
        sections = doc.sections
        for section in sections:
            section.top_margin = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin = Inches(1)
            section.right_margin = Inches(1)
            
            # Configure Footer
            footer = section.footer
            f_para = footer.paragraphs[0]
            f_para.alignment = WD_ALIGN_PARAGRAPH.RIGHT
            f_para.text = ""
            run = f_para.add_run("Generated by Multi-Agent Event Planning Orchestrator | Page ")
            run.font.name = "Arial"
            run.font.size = Pt(8.5)
            run.font.italic = True
            run.font.color.rgb = RGBColor(120, 120, 120)
            
            page_run = f_para.add_run()
            page_run.font.name = "Arial"
            page_run.font.size = Pt(8.5)
            page_run.font.italic = True
            page_run.font.color.rgb = RGBColor(120, 120, 120)
            cls._add_page_number(page_run)

        # Style colors
        primary_color = RGBColor(26, 82, 118) # Deep navy blue
        accent_color = RGBColor(211, 84, 0) # Muted Orange
        dark_text = RGBColor(44, 62, 80) # Dark gray

        # ==========================================
        # 1. COVER PAGE
        # ==========================================
        title_para = doc.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_para.paragraph_format.space_before = Pt(120)
        title_para.paragraph_format.space_after = Pt(10)
        
        title_run = title_para.add_run(event_info.get("name", "Academic Event").upper())
        title_run.font.name = "Georgia"
        title_run.font.size = Pt(28)
        title_run.font.bold = True
        title_run.font.color.rgb = primary_color

        sub_para = doc.add_paragraph()
        sub_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub_para.paragraph_format.space_after = Pt(40)
        sub_run = sub_para.add_run("Master Event Strategy & Orchestration Plan")
        sub_run.font.name = "Georgia"
        sub_run.font.size = Pt(14)
        sub_run.font.italic = True
        sub_run.font.color.rgb = accent_color

        # Horizontal line
        border_table = doc.add_table(rows=1, cols=1)
        border_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        border_cell = border_table.rows[0].cells[0]
        border_cell.width = Inches(5.5)
        cls._set_cell_background(border_cell, "1A5276") # Primary color hex
        border_table.rows[0].height = Pt(4)

        # Metadata Block
        meta_para = doc.add_paragraph()
        meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        meta_para.paragraph_format.space_before = Pt(100)
        meta_para.paragraph_format.line_spacing = 1.3
        
        meta_items = [
            ("Date", event_info.get("date", "2026-05-30")),
            ("Location", event_info.get("location", "Bangalore")),
            ("Guest Count", f"{event_info.get('guests', 100)} attendees"),
            ("Theme", event_info.get("theme", "AI & Technology")),
            ("Budget Tier", event_info.get("budget", "1-5 Lakhs"))
        ]
        for key, val in meta_items:
            k_run = meta_para.add_run(f"{key}: ")
            k_run.font.name = "Arial"
            k_run.font.bold = True
            k_run.font.size = Pt(10.5)
            k_run.font.color.rgb = dark_text
            
            v_run = meta_para.add_run(f"{val}\n")
            v_run.font.name = "Arial"
            v_run.font.size = Pt(10.5)
            v_run.font.color.rgb = dark_text

        doc.add_page_break()

        # ==========================================
        # 2. EXECUTIVE SUMMARY
        # ==========================================
        h1 = doc.add_heading(level=1)
        h1.paragraph_format.space_before = Pt(10)
        h1.paragraph_format.space_after = Pt(8)
        h1_run = h1.add_run("1. Executive Summary")
        h1_run.font.name = "Georgia"
        h1_run.font.color.rgb = primary_color
        h1_run.font.size = Pt(18)
        h1_run.font.bold = True
        
        summary_text = (
            f"This document represents the synthesized planning portfolio for {event_info.get('name', 'the event')}, "
            f"scheduled to be hosted on {event_info.get('date', 'the selected date')} in the vibrant hub of {event_info.get('location', 'the selected city')}. "
            f"Orchestrated by a custom multi-agent cooperative network, this comprehensive brief aggregates venue scouting, speaker selection, "
            f"menus, setup operations, logistics workflows, and communication pipelines into an actionable master deployment blueprint. "
            f"Our primary objective is to cultivate an immersive, seamless, and high-impact experience tailored specifically to the '{event_info.get('theme', 'AI & Technology')}' "
            f"community, welcoming approximately {event_info.get('guests', 100)} distinguished guests within a {event_info.get('budget', '1-5 Lakhs')} budget framework."
        )
        
        sum_p = doc.add_paragraph()
        sum_p.paragraph_format.line_spacing = 1.15
        sum_p.paragraph_format.space_after = Pt(12)
        sum_run = sum_p.add_run(summary_text)
        sum_run.font.name = "Arial"
        sum_run.font.size = Pt(11)
        sum_run.font.color.rgb = dark_text

        # Callout block for key parameters
        callout_table = doc.add_table(rows=1, cols=1)
        callout_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        callout_cell = callout_table.rows[0].cells[0]
        cls._set_cell_background(callout_cell, "F2F4F4")
        cls._set_cell_margins(callout_cell, top=144, bottom=144, left=216, right=216)
        
        cp = callout_cell.paragraphs[0]
        cp.paragraph_format.line_spacing = 1.2
        c_run = cp.add_run("Key Planning Directives:\n")
        c_run.font.name = "Arial"
        c_run.font.bold = True
        c_run.font.size = Pt(10.5)
        c_run.font.color.rgb = primary_color
        
        dir_text = (
            f"• Scale: {event_info.get('guests', 100)} attendees, requiring appropriate safety, seating, and caterer capacity.\n"
            f"• Dietary Provisions: Accommodating {', '.join(event_info.get('dietary', ['No Preference']))}.\n"
            f"• Domain Target: Theme set to '{event_info.get('theme', 'AI & Technology')}', guiding speaker outreach, AV installations, and agendas."
        )
        cd_run = cp.add_run(dir_text)
        cd_run.font.name = "Arial"
        cd_run.font.size = Pt(10)
        cd_run.font.color.rgb = dark_text

        doc.add_page_break()

        # ==========================================
        # 3. MASTER TIMELINE TABLE
        # ==========================================
        h2 = doc.add_heading(level=1)
        h2.paragraph_format.space_before = Pt(10)
        h2.paragraph_format.space_after = Pt(10)
        h2_run = h2.add_run("2. Master Event Timeline")
        h2_run.font.name = "Georgia"
        h2_run.font.color.rgb = primary_color
        h2_run.font.size = Pt(18)
        
        timeline_intro = doc.add_paragraph()
        timeline_intro_run = timeline_intro.add_run(
            "Below is the synchronized master schedule outlining critical stages, specific activities, and the designated teams/agents responsible for execution."
        )
        timeline_intro_run.font.name = "Arial"
        timeline_intro_run.font.size = Pt(10.5)
        timeline_intro_run.font.color.rgb = dark_text
        
        # We parse the timeline from coordinator_data or build a beautiful default timeline table if coordinator data is unstructured
        timeline_items = coordinator_data.get("timeline", [])
        if not timeline_items:
            timeline_items = [
                {"time": "08:00 AM - 09:30 AM", "activity": "AV Set up, Soundcheck, and Banner Installation", "owner": "Logistics Team & AV Vendor"},
                {"time": "09:30 AM - 10:00 AM", "activity": "Guest Registration, Welcome Drinks, & Badge Distribution", "owner": "Logistics / Registration Desk"},
                {"time": "10:00 AM - 10:15 AM", "activity": "Opening Keynote & Event Theme Briefing", "owner": "Lead Speaker & Host"},
                {"time": "10:15 AM - 11:30 AM", "activity": "Technical Presentation / Panel Discussion Session 1", "owner": "Speaker Panelists"},
                {"time": "11:30 AM - 12:00 PM", "activity": "Structured Coffee Break & Networking Session", "owner": "Catering Vendor"},
                {"time": "12:00 PM - 01:30 PM", "activity": "Masterclass / Hands-on Interactive Session", "owner": "Host & Invited Experts"},
                {"time": "01:30 PM - 02:30 PM", "activity": "Networking Lunch Buffet", "owner": "Catering Vendor"},
                {"time": "02:30 PM - 04:00 PM", "activity": "Collaborative Team Work or Q&A Brainstorm Session", "owner": "All Attendees & Facilitators"},
                {"time": "04:00 PM - 04:30 PM", "activity": "Closing Remarks, Certificate Distribution & Thank You", "owner": "Host & Coordinator Agent"},
                {"time": "04:30 PM - 06:00 PM", "activity": "AV Tear-down, Venue Cleaning & Vendor Settlement", "owner": "Logistics Team"}
            ]

        table = doc.add_table(rows=len(timeline_items) + 1, cols=3)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        table.autofit = False
        
        # Format columns width
        col_widths = [Inches(1.8), Inches(3.2), Inches(1.5)]
        for i, width in enumerate(col_widths):
            table.columns[i].width = width

        # Header Row
        hdr_cells = table.rows[0].cells
        headers = ["Time Slot", "Activity Detail", "Responsible Party"]
        for j, text in enumerate(headers):
            hdr_cells[j].text = text
            hdr_cells[j].width = col_widths[j]
            cls._set_cell_background(hdr_cells[j], "1A5276") # Navy Hex
            cls._set_cell_margins(hdr_cells[j], top=120, bottom=120, left=100, right=100)
            
            p = hdr_cells[j].paragraphs[0]
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            r = p.runs[0]
            r.font.name = "Arial"
            r.font.bold = True
            r.font.size = Pt(10)
            r.font.color.rgb = RGBColor(255, 255, 255)

        # Body Rows
        for i, item in enumerate(timeline_items):
            row_cells = table.rows[i + 1].cells
            # Shading alternate rows
            bg_color = "F9EBEA" if i % 2 == 0 else "FFFFFF"
            
            data_fields = [item.get("time", ""), item.get("activity", ""), item.get("owner", "")]
            for j, val in enumerate(data_fields):
                row_cells[j].text = val
                row_cells[j].width = col_widths[j]
                cls._set_cell_background(row_cells[j], bg_color)
                cls._set_cell_margins(row_cells[j], top=80, bottom=80, left=100, right=100)
                
                p = row_cells[j].paragraphs[0]
                p.alignment = WD_ALIGN_PARAGRAPH.LEFT
                if len(p.runs) > 0:
                    r = p.runs[0]
                    r.font.name = "Arial"
                    r.font.size = Pt(9.5)
                    r.font.color.rgb = dark_text
                    if j == 0:
                        r.font.bold = True

        doc.add_page_break()

        # ==========================================
        # 4. VENDOR BRIEF SECTION
        # ==========================================
        h3 = doc.add_heading(level=1)
        h3.paragraph_format.space_before = Pt(10)
        h3.paragraph_format.space_after = Pt(10)
        h3_run = h3.add_run("3. Vendor Briefing & Services")
        h3_run.font.name = "Georgia"
        h3_run.font.color.rgb = primary_color
        h3_run.font.size = Pt(18)

        # Venue Sub-section
        sh1 = doc.add_heading(level=2)
        sh1_run = sh1.add_run("3.1 Venue Recommendations")
        sh1_run.font.name = "Georgia"
        sh1_run.font.size = Pt(13)
        sh1_run.font.color.rgb = accent_color
        
        venue_p = doc.add_paragraph()
        v_intro = "The Venue Scouting Agent recommends the following properties tailored to host our guest checklist and safety protocols:"
        venue_p.add_run(v_intro).font.name = "Arial"
        venue_p.runs[0].font.size = Pt(10.5)
        venue_p.runs[0].font.color.rgb = dark_text

        # Add venue details in formatted paragraphs
        venues_list = venue_data.get("venues", [])
        if not venues_list:
            venues_list = [{"name": "Grand Corporate Plaza", "capacity": "150 attendees", "cost": "₹1,50,000", "details": "High-speed WiFi, modern AV setup, central location."}]
            
        for idx, ven in enumerate(venues_list):
            vp = doc.add_paragraph()
            vp.paragraph_format.left_indent = Inches(0.25)
            vp.paragraph_format.space_after = Pt(6)
            
            bold_run = vp.add_run(f"Option {idx+1}: {ven.get('name', 'Venue Name')}  |  ")
            bold_run.font.bold = True
            bold_run.font.name = "Arial"
            bold_run.font.size = Pt(10)
            
            cap_run = vp.add_run(f"Capacity: {ven.get('capacity', '120')}  |  Cost: {ven.get('cost', '₹1.2L')} \n")
            cap_run.font.italic = True
            cap_run.font.name = "Arial"
            cap_run.font.size = Pt(10)
            
            desc_run = vp.add_run(f"Description: {ven.get('details', 'Full amenities and central parking access.')}")
            desc_run.font.name = "Arial"
            desc_run.font.size = Pt(9.5)
            desc_run.font.color.rgb = dark_text

        # Catering Sub-section
        sh2 = doc.add_heading(level=2)
        sh2_run = sh2.add_run("3.2 Catering Requirements")
        sh2_run.font.name = "Georgia"
        sh2_run.font.size = Pt(13)
        sh2_run.font.color.rgb = accent_color

        cat_p = doc.add_paragraph()
        cat_intro = "The Catering Planning Agent outlines requirements based on strict guest counts and preferences:"
        cat_p.add_run(cat_intro).font.name = "Arial"
        cat_p.runs[0].font.size = Pt(10.5)
        cat_p.runs[0].font.color.rgb = dark_text

        # Display Catering Options
        cat_options = catering_data.get("menus", [])
        if not cat_options:
            cat_options = [{"name": "Standard Fusion Buffet", "cost_head": "₹850 per head", "items": "Continental starters, main course, traditional desserts."}]
            
        for menu in cat_options:
            mp = doc.add_paragraph()
            mp.paragraph_format.left_indent = Inches(0.25)
            mp.paragraph_format.space_after = Pt(6)
            
            m_bold = mp.add_run(f"• {menu.get('name', 'Menu Tier')} ({menu.get('cost_head', '₹1000/head')}):\n")
            m_bold.font.bold = True
            m_bold.font.name = "Arial"
            m_bold.font.size = Pt(10)
            
            m_desc = mp.add_run(f"  Includes: {menu.get('items', 'Starters, main course, drinks, and dessert items.')}")
            m_desc.font.name = "Arial"
            m_desc.font.size = Pt(9.5)
            m_desc.font.color.rgb = dark_text

        doc.add_page_break()

        # ==========================================
        # 5. SPEAKER PROFILES
        # ==========================================
        h4 = doc.add_heading(level=1)
        h4.paragraph_format.space_before = Pt(10)
        h4.paragraph_format.space_after = Pt(10)
        h4_run = h4.add_run("4. Invited Speakers & Panels")
        h4_run.font.name = "Georgia"
        h4_run.font.color.rgb = primary_color
        h4_run.font.size = Pt(18)

        speaker_intro = doc.add_paragraph()
        speaker_intro_run = speaker_intro.add_run(
            f"The Speaker Agent has identified industry leading profiles aligned closely with '{event_info.get('theme', 'AI & Technology')}':"
        )
        speaker_intro_run.font.name = "Arial"
        speaker_intro_run.font.size = Pt(10.5)
        speaker_intro_run.font.color.rgb = dark_text

        speakers = speaker_data.get("speakers", [])
        if not speakers:
            speakers = [
                {"name": "Dr. Aris Thorne", "bio": "Leading researcher in vector spaces and deep learning systems.", "topic": "Next-Gen AI Agents", "fee": "₹50,000"},
                {"name": "Elena Rostova", "bio": "Product Architect specializing in zero-latency serverless pipelines.", "topic": "SaaS Scaling Tactics", "fee": "₹35,000"}
            ]

        for idx, spk in enumerate(speakers):
            sp_p = doc.add_paragraph()
            sp_p.paragraph_format.left_indent = Inches(0.2)
            sp_p.paragraph_format.space_after = Pt(10)
            
            s_name = sp_p.add_run(f"{idx+1}. {spk.get('name', 'Speaker Name')}\n")
            s_name.font.bold = True
            s_name.font.name = "Arial"
            s_name.font.size = Pt(11)
            s_name.font.color.rgb = primary_color
            
            s_meta = sp_p.add_run(f"Session Topic: \"{spk.get('topic', 'N/A')}\"  |  Est. Honorarium: {spk.get('fee', 'N/A')}\n")
            s_meta.font.italic = True
            s_meta.font.name = "Arial"
            s_meta.font.size = Pt(9.5)
            
            s_bio = sp_p.add_run(f"Bio: {spk.get('bio', 'Bio summary and achievements.')}")
            s_bio.font.name = "Arial"
            s_bio.font.size = Pt(9.5)
            s_bio.font.color.rgb = dark_text

        doc.add_page_break()

        # ==========================================
        # 6. LOGISTICS CHECKLIST
        # ==========================================
        h5 = doc.add_heading(level=1)
        h5.paragraph_format.space_before = Pt(10)
        h5.paragraph_format.space_after = Pt(10)
        h5_run = h5.add_run("5. Operations & Logistics Checklist")
        h5_run.font.name = "Georgia"
        h5_run.font.color.rgb = primary_color
        h5_run.font.size = Pt(18)

        log_p = doc.add_paragraph()
        log_run = log_p.add_run("The Logistics Agent has organized operational checklists based on standard Asana milestone structures:")
        log_run.font.name = "Arial"
        log_run.font.size = Pt(10.5)
        log_run.font.color.rgb = dark_text

        # Checklist Items
        checklist_phases = logistics_data.get("checklists", [])
        if not checklist_phases:
            checklist_phases = [
                {
                    "title": "On-Ground Setup",
                    "items": [
                        "Verify dual mic system & AV mixer channels",
                        "Confirm projector compatibility and HDMI connectivity",
                        "Install backdrops, badges, signages & directional banners"
                    ]
                },
                {
                    "title": "Transport & Security",
                    "items": [
                        "Arrange airport shuttle for key speakers",
                        "Ensure registration counter has digital list and printing backups",
                        "Setup designated first-aid post and emergency routes"
                    ]
                }
            ]

        for phase in checklist_phases:
            sh_chk = doc.add_heading(level=2)
            sh_chk_run = sh_chk.add_run(phase.get("title", "Checklist Phase"))
            sh_chk_run.font.name = "Georgia"
            sh_chk_run.font.size = Pt(12)
            sh_chk_run.font.color.rgb = accent_color
            
            for item in phase.get("items", []):
                ch_p = doc.add_paragraph(style='List Bullet')
                ch_p.paragraph_format.space_after = Pt(4)
                r_item = ch_p.add_run(f"[  ]  {item}")
                r_item.font.name = "Arial"
                r_item.font.size = Pt(9.5)
                r_item.font.color.rgb = dark_text

        doc.add_page_break()

        # ==========================================
        # 7. COMMUNICATIONS TEMPLATES
        # ==========================================
        h6 = doc.add_heading(level=1)
        h6.paragraph_format.space_before = Pt(10)
        h6.paragraph_format.space_after = Pt(10)
        h6_run = h6.add_run("6. Communication Pack")
        h6_run.font.name = "Georgia"
        h6_run.font.color.rgb = primary_color
        h6_run.font.size = Pt(18)

        comms_p = doc.add_paragraph()
        comms_run = comms_p.add_run("Copy-paste ready communications drafted by the Communications Agent:")
        comms_run.font.name = "Arial"
        comms_run.font.size = Pt(10.5)
        comms_run.font.color.rgb = dark_text

        templates = comms_data.get("templates", [
            {"title": "Attendee Invite Email", "subject": f"Invitation: {event_info.get('name')}", "body": "Join us for an exciting day..."},
            {"title": "Speaker Outreach Email", "subject": "Guest Speaker Invitation", "body": "We are honored to invite you..."},
            {"title": "Event Reminder", "subject": "Reminder: We are live in 48 hours", "body": "Just a quick reminder..."},
            {"title": "Post-Event Thank You", "subject": "Thank you for attending!", "body": "Thank you for making our event successful..."}
        ])

        for t in templates:
            sh_t = doc.add_heading(level=2)
            sh_t_run = sh_t.add_run(t.get("title", "Email Template"))
            sh_t_run.font.name = "Georgia"
            sh_t_run.font.size = Pt(12)
            sh_t_run.font.color.rgb = accent_color
            
            # Subject
            sub_p = doc.add_paragraph()
            sub_p.paragraph_format.space_after = Pt(4)
            s_label = sub_p.add_run("Subject: ")
            s_label.font.bold = True
            s_label.font.name = "Arial"
            s_label.font.size = Pt(10)
            
            s_text = sub_p.add_run(t.get("subject", "Email Subject Line"))
            s_text.font.italic = True
            s_text.font.name = "Arial"
            s_text.font.size = Pt(10)
            
            # Body box
            body_table = doc.add_table(rows=1, cols=1)
            body_table.alignment = WD_TABLE_ALIGNMENT.CENTER
            body_cell = body_table.rows[0].cells[0]
            cls._set_cell_background(body_cell, "FCF3CF") # Light warm yellow
            cls._set_cell_margins(body_cell, top=100, bottom=100, left=150, right=150)
            
            bp = body_cell.paragraphs[0]
            bp.paragraph_format.line_spacing = 1.15
            b_run = bp.add_run(t.get("body", "Email Body Content"))
            b_run.font.name = "Consolas"
            b_run.font.size = Pt(9)
            b_run.font.color.rgb = dark_text
            
            # Spacing after table
            doc.add_paragraph().paragraph_format.space_before = Pt(8)

        # Save document
        doc.save(output_path)
        print(f"Exported final plan to {output_path}")
        return output_path
